FROM ghcr.io/cirruslabs/flutter:stable AS build

WORKDIR /app/flutter_ai

COPY flutter_ai/pubspec.yaml ./pubspec.yaml
COPY flutter_ai/web ./web

RUN flutter config --enable-web && flutter pub get

COPY flutter_ai/lib ./lib

RUN flutter build web --release --base-href /

FROM nginx:1.27-alpine AS runtime

ENV PORT=80

COPY nginx.flutter-web.conf.template /etc/nginx/templates/default.conf.template
COPY --from=build /app/flutter_ai/build/web /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]